# Generated by Django 5.2 on 2025-05-28 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('posicao', models.IntegerField(default=0)),
                ('em_jogo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JogadorPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.jogador')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Jogadores'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada')], default='aguardando', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('jogador_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_atual', to='jogo.jogador')),
                ('jogadores', models.ManyToManyField(through='jogo.JogadorPartida', to='jogo.jogador')),
            ],
        ),
        migrations.AddField(
            model_name='jogadorpartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.partida'),
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posicao', models.IntegerField(unique=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propriedades', to='jogo.jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('compra', 'Compra de Propriedade'), ('aluguel', 'Pagamento de Aluguel'), ('salario', 'Recebimento de Salário'), ('imposto', 'Pagamento de Imposto')], max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('jogador_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_recebidas', to='jogo.jogador')),
                ('jogador_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_enviadas', to='jogo.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.partida')),
                ('propriedade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jogo.propriedade')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='jogadorpartida',
            unique_together={('jogador', 'partida')},
        ),
    ]
